Repository nextcloud/tasks, pull requests merged in 2019-05, with the labels that each got.

#384 Add comments to unclear translations
  src/components/SortorderDropdown.vue
  src/components/TheDetails.vue
Labels: 3 - to review

#236 Implement drag and drop
  css/src/style.scss
  package-lock.json
  package.json
  src/components/Task.vue
  src/components/TaskDragContainer.vue
  src/components/TheCollections/Calendar.vue
  src/components/TheCollections/General.vue
  src/components/TheCollections/Week.vue
  src/components/TheDetails.vue
  src/store/calendars.js
  src/store/tasks.js
Labels: 3 - to review, feature

#395 Correctly handle all numeric UIDs
  appinfo/info.xml
  package.json
  src/store/calendars.js
Labels: 3 - to review, bug

#400 Open task after creation
  src/store/tasks.js
Labels: 3 - to review, bug, regression

#410 Implement sharing calendars / task lists
  css/src/Calendars/Calendar.scss
  css/src/Calendars/CalendarSharee.scss
  css/src/Calendars/CalendarShares.scss
  css/src/style.scss
  css/tasks.scss
  src/components/CalendarShare.vue
  src/components/CalendarSharee.vue
  src/components/TheList.vue
  src/store/calendars.js
Labels: 3 - to review, enhancement, feature

#412 Add support for tasks privacy settings
  css/src/style.scss
  img/src/color/privacy.svg
  src/components/TheDetails.vue
  src/models/task.js
  src/store/tasks.js
Labels: 3 - to review, feature

#405 Fix editing task properties in details view
  src/components/TheDetails.vue
Labels: 3 - to review, bug, regression

#422 Show subtasks when task is open in details view
  src/components/Task.vue
Labels: 3 - to review, bug, regression, vue

#424 Prevent accidental task dragging on mobile
  src/components/TaskDragContainer.vue
Labels: 3 - to review, bug

#426 Comply with our npm guidelines
  Makefile
  package.json
Labels: 3 - to review, Cleanup

#425 Improve drag and drop experience
  css/src/style.scss
  src/components/TaskDragContainer.vue
Labels: design, enhancement
