Repository nextcloud/tasks, pull requests merged in 2020-02, with the labels that each got.

#853 Use alias for jest file resolution
  package.json
  tests/javascript/unit/components/TheCollections/General.spec.js
  tests/javascript/unit/components/TheCollections/Week.spec.js
  tests/javascript/unit/models/task.spec.js
  tests/javascript/unit/setupStore.js
  tests/javascript/unit/store/storeHelper.spec.js
Labels: Cleanup

#818 Use the vue-components for app-navigation and app-content
  css/src/style.scss
  src/App.vue
  src/components/AppNavigation/CalendarShare.vue
  src/components/AppNavigation/CalendarSharee.vue
  src/components/AppNavigation/Colorpicker.vue
  src/components/AppNavigation/List.vue
  src/components/AppNavigation/ListItemCalendar.vue
  src/components/AppNavigation/TheSettings.vue
  src/components/Confirmation.vue
  src/components/TaskBody.vue
  src/components/TaskDragContainer.vue
  src/components/TheList.vue
  src/main.js
  src/router.js
Labels: 3 - to review, Cleanup, bug, design, enhancement

#844 Move to github actions 1
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .travis.yml
  composer.json
  tests/javascript/unit/.eslintrc.js
Labels: 2 - developing, Cleanup

#863 Fix uncaught exception: object error on navigation
  src/components/TaskBody.vue
Labels: 3 - to review, bug

#865 Use new start and due date icons in details view
  css/src/style.scss
  img/src/bw/duedate.svg
  img/src/bw/startdate.svg
  img/src/color/duedate-due.svg
  img/src/color/duedate-overdue.svg
  img/src/color/startdate-due.svg
  img/src/color/startdate-overdue.svg
  src/components/TheDetails.vue
Labels: 3 - to review, Cleanup

#868 Adjust sprite file naming to prevent collision with server naming scheme
  .gitignore
  css/src/style.scss
  img/arrow-left.svg
  img/arrow-right.svg
  img/src/bw/random.svg
  img/src/bw/settings.svg
  img/src/bw/sort-down.svg
  img/src/bw/sort-up.svg
  lib/Service/CollectionsService.php
  src/components/AppNavigation/List.vue
  src/components/TaskBody.vue
  src/components/TheDetails.vue
  svg-sprite-bw.json
  svg-sprite-bw.tmpl
  svg-sprite-color.json
  tests/php/unit/Service/CollectionsServiceTest.php
Labels: 3 - to review, Cleanup

#862 Prevent editing not public tasks in lists shared with me
  css/src/Calendars/CalendarSharee.scss
  css/src/Calendars/CalendarShares.scss
  css/src/style.scss
  css/tasks.scss
  src/App.vue
  src/components/AppNavigation/CalendarShare.vue
  src/components/AppNavigation/CalendarSharee.vue
  src/components/AppNavigation/ListItemCalendar.vue
  src/components/TheDetails.vue
  src/models/principal.js
  src/store/calendars.js
  src/store/principals.js
  src/store/store.js
  src/store/tasks.js
  tests/javascript/unit/setupStore.js
Labels: 3 - to review, bug

#877 Correctly translate task status strings
  src/store/tasks.js
Labels: 3 - to review, bug

#878 Run actions on push as well
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: bug
