Repository nextcloud/tasks, pull requests merged in 2021-06, with the labels that each got.

#1636 Create tasks in correct list
  src/components/Header.vue
  src/store/calendars.js
  src/views/AppContent/Calendar.vue
  src/views/AppContent/General.vue
  src/views/AppContent/Week.vue
Labels: bug

#1637 Update dependencies
  package-lock.json
  package.json
Labels: 3 - to review, dependencies

#1639 Update jest to 27
  package-lock.json
  package.json
Labels: Cleanup, dependencies

#1640 Don't explicitly require babel object rest spread
  package-lock.json
  package.json
Labels: Cleanup, dependencies

#1642 Use correct babel configuration
  .babelrc.js
  babel.config.js
  package-lock.json
  package.json
  tests/javascript/unit/setup.js
Labels: Cleanup

#1647 Fix makefile
  Makefile
Labels: Cleanup

#1641 Add Dashboard widget
  Makefile
  img/tasks-dark.svg
  lib/AppInfo/Application.php
  lib/Dashboard/TasksWidget.php
  package-lock.json
  package.json
  src/css/dashboard.scss
  src/dashboard.js
  src/views/Dashboard.vue
  webpack.js
Labels: 3 - to review, enhancement, feature

#1654 Fix usage of generateOcsUrl
  src/components/AppNavigation/CalendarShare.vue
Labels: bug

#1655 Remove support for Nextcloud server v19
  appinfo/info.xml
  src/main.js
Labels: 3 - to review, Cleanup

#1661 Create rebase comment
  .github/workflows/command-rebase.yml
Labels: 3 - to review

#1662 Remove scrutinizer config
  .scrutinizer.yml
Labels: Cleanup

#1663 Unify task deletion undo
  src/components/TaskBody.vue
  src/models/task.js
  src/store/tasks.js
  src/views/AppSidebar.vue
Labels: Cleanup, enhancement

#1668 Adjust the app-navigation-toggle alignment
  css/tasks.scss
  src/components/Header.vue
Labels: design, enhancement
