Repository nextcloud/tasks, pull requests merged in 2021-09, with the labels that each got.

#1775 Use @nextcloud/l10n everywhere
  src/App.vue
  src/components/AppNavigation/AppNavigationSettings.vue
  src/components/AppNavigation/CalendarShare.vue
  src/components/AppNavigation/CalendarSharee.vue
  src/components/AppNavigation/ListItemCalendar.vue
  src/components/AppSidebar/DatetimePickerItem.vue
  src/components/AppSidebar/NotesItem.vue
  src/components/AppSidebar/SliderItem.vue
  src/components/AppSidebar/TagsItem.vue
  src/components/DeleteCompletedModal.vue
  src/components/Header.vue
  src/components/LoadCompletedButton.vue
  src/components/SortorderDropdown.vue
  src/components/TaskBody.vue
  src/main.js
  src/views/AppContent/Calendar.vue
  src/views/AppContent/Week.vue
  src/views/AppNavigation.vue
  src/views/AppSidebar.vue
Labels: Cleanup

#1777 increase size of `load all completed tasks` button
  src/components/DeleteCompletedModal.vue
  src/components/LoadCompletedButton.vue
Labels: enhancement, design, 3 - to review

#1789 Adjust material design icon size to 20
  src/components/AppNavigation/AppNavigationSettings.vue
  src/components/AppNavigation/CalendarSharee.vue
  src/components/AppNavigation/ListItemCalendar.vue
  src/components/AppNavigation/Trashbin.vue
  src/components/AppSidebar/DatetimePickerItem.vue
  src/components/AppSidebar/MultiselectOption.vue
  src/components/AppSidebar/SliderItem.vue
  src/components/AppSidebar/TagsItem.vue
  src/components/Header.vue
  src/components/SortorderDropdown.vue
  src/components/TaskBody.vue
  src/components/TaskCreateDialog.vue
  src/components/TaskStatusDisplay.vue
  src/views/AppNavigation.vue
  src/views/AppSidebar.vue
Labels: design, 3 - to review

#1795 Use linkify directive from nextclud/vue
  package-lock.json
  package.json
  src/components/TaskBody.vue
  src/directives/linkify.js
Labels: Cleanup, 3 - to review, dependencies

#1790 complete task in dashbaord
  src/App.vue
  src/dashboard.js
  src/views/Dashboard.vue
Labels: 3 - to review

#1797 Fix undefined Tasks version then creating task from Dashboard or Talk
  src/dashboard.js
  src/talk.js
Labels: bug

#1801 Update link to server's contribution guidelines
  CONTRIBUTING.md
Labels: 3 - to review

#1804 Update nextcloud/vue, cleanup hacks
  package-lock.json
  package.json
  src/components/AppNavigation/AppNavigationSettings.vue
  src/components/AppNavigation/CalendarSharee.vue
  src/components/AppNavigation/Trashbin.vue
  src/main.js
  src/views/AppNavigation.vue
Labels: Cleanup, 3 - to review, dependencies
