Repository nextcloud/tasks, pull requests merged in 2021-12, with the labels that each got.

#1844 Update npm and node engines versions
  package.json
Labels: dependencies

#1873 Don't break trashbin if calendar is undefined
  src/components/AppNavigation/Trashbin.vue
Labels: bug

#1876 Correctly show untitled items in trash bin
  src/components/AppNavigation/Trashbin.vue
Labels: bug

#1877 Always show sharing icon for shared lists
  src/components/AppNavigation/ListItemCalendar.vue
Labels: enhancement

#1889 Fix trash bin icon size
  src/components/AppNavigation/Trashbin.vue
Labels: bug

#1895 Correctly align plus icon in task input field
  src/components/Header.vue
Labels: bug, design
