Repository nextcloud/tasks, pull requests merged in 2021-07, with the labels that each got.

#1649 Create task from Talk message
  css/tasks-talk.scss
  lib/AppInfo/Application.php
  lib/Listeners/BeforeTemplateRenderedListener.php
  src/components/AppSidebar/CalendarPickerItem.vue
  src/components/TaskCreateDialog.vue
  src/helpers/selector.js
  src/store/calendars.js
  src/store/tasks.js
  src/talk.js
  tests/javascript/unit/OC.js
  webpack.js
Labels: 2 - developing, enhancement, help wanted

#1675 Add trashbin GUI
  package-lock.json
  package.json
  src/App.vue
  src/components/AppNavigation/Moment.vue
  src/components/AppNavigation/Trashbin.vue
  src/models/calendarObject.js
  src/models/consts.js
  src/store/calendars.js
  src/utils/logger.js
  src/views/AppNavigation.vue
  src/views/Dashboard.vue
Labels: 2 - developing, enhancement, feature

#1702 Show task title in appsidebar title tooltip
  src/views/AppSidebar.vue
Labels: enhancement

#1703 Open notes tab in appsidebar on notes icon click
  src/components/TaskBody.vue
  src/router.js
  src/views/AppSidebar.vue
Labels: 3 - to review, enhancement

#1705 Add plus icon to task input field
  src/components/Header.vue
  src/components/TaskBody.vue
Labels: design, enhancement

#1708 Fix task creation from talk message
  src/components/TaskCreateDialog.vue
Labels: bug

#1709 Improve task create dialog styling
  src/components/TaskCreateDialog.vue
Labels: design

#1716 Don't overwrite title if navigating while editing
  src/views/AppSidebar.vue
Labels: 3 - to review, bug

#1724 Use correct icon in dark theme dashboard
  src/css/dashboard.scss
Labels: bug

#1725 Correctly align settings labels
  src/components/AppNavigation/AppNavigationSettings.vue
  src/views/AppNavigation.vue
Labels: bug

#1726 Don't show trash bin header while loading or empty
  src/components/AppNavigation/Trashbin.vue
Labels: bug
