Repository nextcloud/tasks, pull requests merged in 2022-03, with the labels that each got.

#1935 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#1936 Updating node.yml workflow from template
  .github/workflows/node.yml
Labels: dependencies

#1933 Use material design checkboxes
  src/components/TaskBody.vue
  src/components/TaskCheckbox.vue
  src/views/AppSidebar.vue
Labels: design, 3 - to review

#1937 update modal sizes after vue 5.1
  src/components/AppNavigation/Trashbin.vue
  src/components/DeleteCompletedModal.vue
  src/components/TaskCreateDialog.vue
Labels: enhancement, design, 3 - to review

#1941 Rename download to export
  src/components/AppNavigation/ListItemCalendar.vue
  src/views/AppSidebar.vue
Labels: design, 3 - to review

#1943 Load all calendars for trash bin
  src/App.vue
  src/components/AppNavigation/Trashbin.vue
  src/store/calendars.js
  src/store/collections.js
  src/store/tasks.js
  src/views/Dashboard.vue
Labels: bug, Cleanup

#1944 Bump @nextcloud/moment
  package-lock.json
  package.json
Labels: bug

#1945 Bump @nextcloud/vue
  package-lock.json
  package.json
Labels: dependencies

#1948 Don't open sidebar when completing task
  src/components/TaskBody.vue
Labels: bug
