Repository nextcloud/tasks, pull requests merged in 2022-08, with the labels that each got.

#2057 Use vue button in dashboard widget
  src/views/Dashboard.vue
Labels: 3 - to review

#2058 Bump webpack from 5.67.0 to 5.74.0
  package-lock.json
Labels: 3 - to review, dependencies

#2060 Bump @nextcloud/vue to 6.0.0-beta.1
  package-lock.json
  package.json
  src/views/Dashboard.vue
Labels: bug, dependencies

#2059 Update npm and node engines versions
  package.json
Labels: dependencies

#1820 Use nextcloud/vue buttons
  .github/workflows/phpunit.yml
  appinfo/info.xml
  src/components/AppNavigation/Trashbin.vue
  src/components/DeleteCompletedModal.vue
  src/components/LoadCompletedButton.vue
  src/components/TaskCreateDialog.vue
Labels: enhancement, design, 3 - to review

#2072 Use empty content icon slots in dashboard
  src/components/TaskIcon.vue
  src/views/Dashboard.vue
Labels: bug, 3 - to review

#2080 Bump nextcloud/vue from 6.0.0-beta.2 to 6.0.0-beta.3
  package-lock.json
  package.json
  src/App.vue
  src/components/AppNavigation/AppNavigationSettings.vue
  src/components/AppNavigation/CalendarShare.vue
  src/components/AppNavigation/CalendarSharee.vue
  src/components/AppNavigation/ListItemCalendar.vue
  src/components/AppNavigation/Trashbin.vue
  src/components/AppSidebar/CalendarPickerItem.vue
  src/components/AppSidebar/CalendarPickerOption.vue
  src/components/AppSidebar/DatetimePickerItem.vue
  src/components/AppSidebar/MultiselectItem.vue
  src/components/AppSidebar/SliderItem.vue
  src/components/AppSidebar/TagsItem.vue
  src/components/DeleteCompletedModal.vue
  src/components/LoadCompletedButton.vue
  src/components/SortorderDropdown.vue
  src/components/TaskBody.vue
  src/components/TaskCreateDialog.vue
  src/components/TaskStatusDisplay.vue
  src/mixins/editableItem.js
  src/views/AppNavigation.vue
  src/views/AppSidebar.vue
  src/views/Dashboard.vue
Labels: 3 - to review, dependencies

#2084 Use NcCounterBubble
  src/components/AppNavigation/ListItemCalendar.vue
  src/views/AppNavigation.vue
Labels: enhancement, design, 3 - to review

#2085 Use NcProgressBar
  src/components/DeleteCompletedModal.vue
  src/components/TaskBody.vue
Labels: enhancement, design, 3 - to review

#2090 Fix sharing tooltip
  src/components/AppNavigation/ListItemCalendar.vue
Labels: enhancement, 3 - to review
