Repository nextcloud/tasks, pull requests merged in 2022-07, with the labels that each got.

#2053 Rename settings to tasks settings
  src/components/AppNavigation/AppNavigationSettings.vue
Labels: 3 - to review

#2007 Adjust AppNavigation to new AppNavigationItem structure
  package-lock.json
  package.json
  src/components/AppNavigation/CalendarShare.vue
  src/components/AppNavigation/ListItemCalendar.vue
  src/views/AppNavigation.vue
Labels: 3 - to review, dependencies

#1985 Migrate to DashboardWidget from nextcloud/vue
  package-lock.json
  package.json
  src/views/Dashboard.vue
Labels: Cleanup, 3 - to review, dependencies

#2017 Don't show dashboard actions for readonly tasks
  src/views/Dashboard.vue
Labels: enhancement, dependencies
