Repository nextcloud/tasks, pull requests merged in 2022-05, with the labels that each got.

#2002 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#1998 Display tasks with future start date dimly
  src/components/TaskBody.vue
Labels: enhancement, 3 - to review

#2011 Fix AppNavigationItems HTML structure
  src/components/AppNavigation/ListItemCalendar.vue
  src/views/AppNavigation.vue
Labels: bug

#2015 Bump jest from 27.5.1 to 28.1.0
  package-lock.json
  package.json
Labels: dependencies, javascript

#2016 Move SCSS into components
  css/tasks.scss
  img/circle.svg
  package-lock.json
  package.json
  src/App.vue
  src/components/AppNavigation/CalendarSharee.vue
  src/views/AppContent/Calendar.vue
  src/views/AppContent/General.vue
  src/views/AppContent/Week.vue
  src/views/AppContent/task-list.scss
  src/views/AppNavigation.vue
  templates/main.php
Labels: Cleanup
