Repository nextcloud/tasks, pull requests merged in 2022-04, with the labels that each got.

#1964 Move @vue/test-utils to dev dependencies
  package-lock.json
  package.json
Labels: Cleanup, dependencies

#1968 Bump @nextcloud/eslint-config from 7.0.2 to 8.0.0
  package-lock.json
  package.json
  src/App.vue
  src/components/AppNavigation/CalendarShare.vue
  src/components/AppNavigation/ListItemCalendar.vue
  src/components/AppNavigation/Trashbin.vue
  src/components/AppSidebar/CalendarPickerItem.vue
  src/components/AppSidebar/DatetimePickerItem.vue
  src/components/AppSidebar/MultiselectItem.vue
  src/components/AppSidebar/NotesItem.vue
  src/components/AppSidebar/SliderItem.vue
  src/components/AppSidebar/TagsItem.vue
  src/components/Header.vue
  src/components/TaskBody.vue
  src/components/TaskCreateDialog.vue
  src/components/TaskDragContainer.vue
  src/dashboard.js
  src/helpers/selector.js
  src/main.js
  src/mixins/editableItem.js
  src/models/calendarObject.js
  src/router.js
  src/store/calendars.js
  src/store/collections.js
  src/store/principals.js
  src/store/settings.js
  src/store/store.js
  src/store/storeHelper.js
  src/store/tasks.js
  src/talk.js
  src/utils/color.js
  src/views/AppContent/Calendar.vue
  src/views/AppContent/Collections.vue
  src/views/AppContent/General.vue
  src/views/AppContent/Week.vue
  src/views/AppNavigation.vue
  src/views/AppSidebar.vue
  src/views/Dashboard.vue
  tests/javascript/unit/utils/url.spec.js
Labels: 3 - to review, dependencies

#1972 Cleanup test configuration
  package.json
  tests/javascript/unit/setup.js
Labels: Cleanup, 3 - to review

#1973 Check that taskUri is defined before searching
  src/views/AppSidebar.vue
Labels: Cleanup

#1974 Use try/catch block to copy to clipboard
  src/components/AppNavigation/ListItemCalendar.vue
Labels: Cleanup

#1975 Don't use deprecated filters anymore
  src/components/AppNavigation/ListItemCalendar.vue
  src/views/AppNavigation.vue
Labels: Cleanup

#1976 Use tooltip directive from nextcloud/vue
  package-lock.json
  package.json
  src/components/AppNavigation/ListItemCalendar.vue
  src/components/DeleteCompletedModal.vue
  src/components/SortorderDropdown.vue
  src/main.js
  src/views/AppNavigation.vue
  tests/javascript/unit/views/AppContent/General.spec.js
  tests/javascript/unit/views/AppContent/Week.spec.js
Labels: Cleanup

#1978 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies
