Repository nextcloud/tasks, pull requests merged in 2023-12, with the labels that each got.

#2321 chore(vite): Migrate from webpack to vite
  .eslintrc.cjs
  .gitignore
  Makefile
  babel.config.cjs
  css/tasks-icon.css
  img/color_picker.svg
  lib/Dashboard/TasksWidget.php
  lib/Listeners/BeforeTemplateRenderedListener.php
  package-lock.json
  package.json
  src/components/AppNavigation/Colorpicker.vue
  src/css/dashboard.scss
  src/dashboard.js
  src/main.js
  src/talk.js
  src/views/AppSidebar.vue
  templates/main.php
  tests/assets/loadAsset.js
  tests/javascript/unit/.eslintrc.cjs
  vite.config.mjs
  webpack.config.js
Labels: enhancement, 3 - to review

#2331 Bump `@nextcloud/vue` from `7.12.6` to `8.3.0`
  appinfo/info.xml
  package-lock.json
  package.json
  src/App.vue
  src/components/AppNavigation/AppNavigationSettings.vue
  src/components/AppNavigation/ListItemCalendar.vue
  src/components/AppSidebar/CalendarPickerItem.vue
  src/components/AppSidebar/DateTimePickerItem.vue
  src/components/AppSidebar/MultiselectItem.vue
  src/components/AppSidebar/SliderItem.vue
  src/components/AppSidebar/TagsItem.vue
  src/components/HeaderBar.vue
  src/components/TaskBody.vue
  src/components/TaskCreateDialog.vue
  src/talk.js
  src/views/AppContent/Calendar.vue
  src/views/AppContent/General.vue
  src/views/AppContent/Week.vue
  src/views/AppContent/task-list.scss
  src/views/AppSidebar.vue
Labels: bug, design, 2 - developing, dependencies

#2410 chore: don't bind translate to vue prototype
  src/dashboard.js
  src/talk.js
Labels: Cleanup, 3 - to review

#2419 chore: update workflows from templates
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node-test.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-sqlite.yml
  composer.json
  composer.lock
  lib/Controller/CollectionsController.php
Labels: dependencies, automated, 3. to review

#2420 chore: bump nextcloud/vue from 8.3.0 to 8.4.0
  package-lock.json
  package.json
Labels: 3 - to review, dependencies

#2409 chore(vitest): migrate from `jest` to `vitest`
  package-lock.json
  package.json
  src/components/TaskDragContainer.vue
  src/dashboard.js
  src/main.js
  src/store/tasks.js
  src/talk.js
  tests/assets/ics/vcalendars/calendar1/vcalendar-vtodo1.ics
  tests/assets/ics/vcalendars/calendar1/vcalendar-vtodo2.ics
  tests/assets/ics/vcalendars/calendar1/vcalendar-vtodo3.ics
  tests/assets/ics/vcalendars/calendar1/vcalendar-vtodo3_1.ics
  tests/assets/ics/vcalendars/calendar1/vcalendar-vtodo3_1_1.ics
  tests/assets/ics/vcalendars/calendar1/vcalendar-vtodo3_2.ics
  tests/assets/ics/vcalendars/calendar1/vcalendar-vtodo4.ics
  tests/assets/ics/vcalendars/calendar1/vcalendar-vtodo4_1.ics
  tests/assets/ics/vcalendars/calendar1/vcalendar-vtodo5.ics
  tests/assets/ics/vcalendars/calendar1/vcalendar-vtodo6.ics
  tests/assets/ics/vcalendars/calendar1/vcalendar-vtodo7.ics
  tests/assets/ics/vcalendars/calendar2/vcalendar-vtodo1.ics
  tests/assets/ics/vcalendars/calendar2/vcalendar-vtodo2.ics
  tests/assets/ics/vcalendars/calendar2/vcalendar-vtodo3.ics
  tests/assets/ics/vcalendars/calendar2/vcalendar-vtodo4.ics
  tests/assets/ics/vcalendars/calendar2/vcalendar-vtodo4_1.ics
  tests/assets/ics/vcalendars/calendar2/vcalendar-vtodo4_2.ics
  tests/assets/ics/vcalendars/calendar2/vcalendar-vtodo4_2_1.ics
  tests/assets/ics/vcalendars/vcalendar-categories-multiple.ics
  tests/assets/ics/vcalendars/vcalendar-categories-none.ics
  tests/assets/ics/vcalendars/vcalendar-categories-single.ics
  tests/assets/ics/vcalendars/vcalendar-default.ics
  tests/assets/ics/vcalendars/vcalendar-due-2015.ics
  tests/assets/ics/vcalendars/vcalendar-due-2018.ics
  tests/assets/ics/vcalendars/vcalendar-due-2019.ics
  tests/assets/ics/vcalendars/vcalendar-due-undefined.ics
  tests/assets/ics/vcalendars/vcalendar-reltype-child.ics
  tests/assets/ics/vcalendars/vcalendar-reltype-default.ics
  tests/assets/ics/vcalendars/vcalendar-reltype-parent.ics
  tests/assets/ics/vcalendars/vcalendar-reltype-sibling.ics
  tests/assets/ics/vcalendars/vcalendar-sortOrder1.ics
  tests/assets/ics/vcalendars/vcalendar-sortOrder2.ics
  tests/assets/ics/vcalendars/vcalendar-sortOrder6.ics
  tests/assets/ics/vcalendars/vcalendar-sortOrderByCreated1.ics
  tests/assets/ics/vcalendars/vcalendar-sortOrderByCreated2.ics
  tests/assets/loadAsset.js
  tests/javascript/unit/.eslintrc.cjs
  tests/javascript/unit/components/Colorpicker.spec.js
  tests/javascript/unit/components/TaskDragContainer.spec.js
  tests/javascript/unit/models/task.spec.js
  tests/javascript/unit/setup.js
  tests/javascript/unit/setupStore.js
  tests/javascript/unit/store/storeHelper.spec.js
  tests/javascript/unit/utils/textToTask.spec.js
  tests/javascript/unit/utils/url.spec.js
  tests/javascript/unit/views/AppContent/General.spec.js
  tests/javascript/unit/views/AppContent/Week.spec.js
  tests/javascript/unit/views/AppSidebar.spec.js
  vite.config.mjs
Labels: Cleanup, 3 - to review, dependencies

#2423 chore: ensure router is ready in tests
  tests/javascript/unit/views/AppContent/General.spec.js
  tests/javascript/unit/views/AppContent/Week.spec.js
Labels: Cleanup, 3 - to review

#2424 fix: correct navigation toggle position
  src/App.vue
Labels: 3 - to review

#2425 feat: extract tags from task summary
  src/store/storeHelper.js
  src/store/tasks.js
  tests/javascript/unit/store/storeHelper.spec.js
Labels: enhancement, feature, 3 - to review

#2426 feat: unify the appearance of tags in task body with sidebar
  src/components/TaskBody.vue
Labels: design, 3 - to review
