Repository nextcloud/tasks, pull requests merged in 2024-01, with the labels that each got.

#2429 feat: treat tasks with `STATUS:COMPLETED` as completed
  src/models/task.js
  tests/assets/loadAsset.js
  tests/javascript/unit/models/task.spec.js
Labels: enhancement, 3 - to review

#2430 fix: correctly show task body corners when tasks are hidden
  src/components/TaskBody.vue
Labels: bug, design, 3 - to review

#2427 feat: implement filtering by tags
  src/components/FilterDropdown.vue
  src/components/HeaderBar.vue
  src/components/TaskBody.vue
  src/models/task.js
  src/store/calendars.js
  src/store/collections.js
  src/store/storeHelper.js
  src/store/tasks.js
  tests/javascript/unit/models/task.spec.js
Labels: enhancement, design, feature, 3 - to review

#2431 fix: allow to clear global search in filter menu
  src/components/FilterDropdown.vue
Labels: enhancement, 3 - to review

#2432 fix: use TagMultiple icon consistently
  src/components/AppSidebar/TagsItem.vue
  src/main.js
  src/views/AppSidebar.vue
Labels: enhancement, design, 3 - to review

#2433 feat: sort tags in dropdown alphabetically
  src/store/tasks.js
Labels: enhancement, 3 - to review

#2435 fix: correctly translate the loading completed tooltip
  src/components/LoadCompletedButton.vue
Labels: bug, 3 - to review

#2434 feat: use NcButton to toggle completed tasks visibility
  src/views/AppContent/Calendar.vue
  src/views/AppContent/task-list.scss
Labels: enhancement, design, 3 - to review

#2437 fix: don't show empty category for empty CATEGORIES param
  src/models/task.js
  tests/assets/loadAsset.js
  tests/javascript/unit/models/task.spec.js
Labels: bug, 3 - to review

#2436 feat: show link to Deck for deck cards
  src/views/AppSidebar.vue
Labels: enhancement, 3 - to review

#2438 feat: show start date as label in task body
  src/components/TaskBody.vue
  src/utils/dateStrings.js
  src/views/AppSidebar.vue
Labels: feature, 3 - to review

#2439 fix: use `NcDateTime` to show time in trashbin
  src/components/AppNavigation/Moment.vue
  src/components/AppNavigation/Trashbin.vue
Labels: bug, 3 - to review

#2440 feat: implement sorting trashbin items
  src/components/AppNavigation/Trashbin.vue
  src/store/storeHelper.js
Labels: enhancement, feature, 3 - to review

#2443 feat: implement task URL
  src/models/task.js
  src/store/tasks.js
  src/views/AppSidebar.vue
  tests/assets/loadAsset.js
  tests/javascript/unit/models/task.spec.js
Labels: feature, 3 - to review

#2444 fix: import TaskBody globally
  src/components/TaskDragContainer.vue
  src/main.js
  tests/javascript/unit/views/AppContent/General.spec.js
  tests/javascript/unit/views/AppContent/Week.spec.js
Labels: bug, 3 - to review

#2445 fix: load missing CSS file
  templates/main.php
Labels: bug, 3 - to review

#2447 fix: make tag left-right padding symmetric
  src/components/TaskBody.vue
Labels: bug, design, 3 - to review

#2446 fix: correctly handle timezones
  src/models/task.js
  src/store/storeHelper.js
  src/store/tasks.js
Labels: bug, enhancement, 3 - to review

#2450 chore(deps): bump nextcloud/moment to 1.3.0
  package-lock.json
  package.json
Labels: bug, 3 - to review, dependencies

#2451 chore(deps): bump vitest and happy-dom
  package-lock.json
  package.json
Labels: 3 - to review, dependencies

#2455 Update npm and node engines versions
  package.json
Labels: dependencies

#2464 feat: use circular progress bar instead of linear bar
  src/components/NcProgressBar.vue
  src/components/TaskBody.vue
Labels: enhancement, design, 3 - to review

#2467 fix: move progress bar to the right
  src/components/TaskBody.vue
Labels: design, 3 - to review

#2468 fix: correctly set start and due date, toggle all-day
  src/models/task.js
  src/store/storeHelper.js
  src/views/AppSidebar.vue
Labels: bug, 3 - to review

#2470 chore(dep): bump nextcloud/vue to 8.5.0
  lib/Dashboard/TasksWidget.php
  package-lock.json
  package.json
  src/components/TaskBody.vue
  templates/main.php
Labels: 3 - to review, dependencies

#2473 chore(dep): bump various dependencies, regenerate package-lock.json
  package-lock.json
  package.json
Labels: 3 - to review, dependencies
