Repository nextcloud/tasks, pull requests merged in 2024-08, with the labels that each got.

#2635 fix: select color when creating list
  src/views/AppNavigation.vue
Labels: bug, regression

#2618 chore: update workflows from templates
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node-test.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-sqlite.yml
Labels: dependencies, automated, 3. to review

#2636 fix: correctly set allday and keep timezone
  src/models/task.js
Labels: bug, regression, 3. to review

#2637 fix: do not use buggy toJSDate
  src/models/task.js
Labels: bug, 3. to review

#2638 fix: correctly handle timezone of completed, created and modified date
  src/models/task.js
Labels: bug, 3. to review

#2639 fix: bring back titles in sidebar
  src/views/AppSidebar.vue
Labels: bug, regression, 3. to review

#2640 chore(deps): bump nextcloud-vue from 9.0.0-alpha.2 to 9.0.0-alpha.5
  package-lock.json
  package.json
Labels: dependencies, 3. to review

#2641 chore(deps): bump calendar-js from 6.1.0 to 8.0.0
  package-lock.json
  package.json
Labels: dependencies, 3. to review

#2642 chore(deps): migrate to stable vite-config and eslint-config
  .eslintrc.cjs
  package-lock.json
  package.json
  src/App.vue
  src/components/AppNavigation/CalendarShare.vue
  src/components/AppSidebar/NotesItem.vue
  src/components/TaskDragContainer.vue
Labels: dependencies, 3. to review

#2643 fix: run npm audit fix
  package-lock.json
Labels: dependencies, 3. to review

#2644 Move GH action to workflows folder
  .github/pr-feedback.yml
  .github/workflows/pr-feedback.yml
Labels: 3. to review

#2661 chore: update workflows from templates
  .github/workflows/lint-eslint.yml
  .github/workflows/node.yml
Labels: dependencies, automated, 3. to review

#2667 fix: no need to include CSS chunks separately
  lib/Dashboard/TasksWidget.php
  lib/Listeners/BeforeTemplateRenderedListener.php
  templates/main.php
Labels: bug, regression, 3. to review
