Repository nextcloud/tasks, pull requests merged in 2025-01, with the labels that each got.

#2686 feat: allow editing completion date
  src/components/AppSidebar/DateTimePickerItem.vue
  src/models/task.js
  src/store/tasks.js
  src/views/AppSidebar.vue
  tests/javascript/unit/views/AppSidebar.spec.js
Labels: feature, 2. developing, feedback-requested

#2707 chore: remove unused jstimezonedetect npm dependency
  package-lock.json
  package.json
Labels: Cleanup, dependencies, 3. to review, feedback-requested

#2746 chore(deps): bump calendar-js from 8.0.2 to 8.0.3
  package-lock.json
  package.json
Labels: dependencies, 3. to review

#2752 fix: run npm audit fix
  package-lock.json
Labels: dependencies, 3. to review

#2758 fix: correctly save and create reminders
  src/components/AppSidebar/Alarm/AlarmList.vue
  src/models/task.js
Labels: bug, 3. to review

#2753 fix: adjust to changed counter bubble behavior
  src/components/AppNavigation/ListItemCalendar.vue
  src/views/AppNavigation.vue
Labels: bug, dependencies, 3. to review

#2766 fix: remove empty placeholder from translation
  src/components/TaskBody.vue
  src/utils/dateStrings.js
Labels: bug, 3. to review

#2767 fix: task create dialog in Talk
  lib/Listeners/BeforeTemplateRenderedListener.php
  src/components/AppSidebar/CalendarPickerItem.vue
Labels: bug, regression, 3. to review

#2768 chore(deps): bump nextcloud/vue to 9.0.0-alpha.6
  package-lock.json
  package.json
  src/App.vue
  src/components/AppNavigation/AppNavigationSettings.vue
  src/components/AppNavigation/CalendarShare.vue
  src/components/AppNavigation/CalendarSharee.vue
  src/components/AppNavigation/ListItemCalendar.vue
  src/components/AppNavigation/Trashbin.vue
  src/components/AppSidebar/CalendarPickerItem.vue
  src/components/AppSidebar/CalendarPickerOption.vue
  src/components/AppSidebar/DateTimePickerItem.vue
  src/components/AppSidebar/MultiselectItem.vue
  src/components/AppSidebar/TagsItem.vue
  src/components/AppSidebar/TextItem.vue
  src/components/CreateMultipleTasksDialog.vue
  src/components/DeleteCompletedModal.vue
  src/components/FilterDropdown.vue
  src/components/HeaderBar.vue
  src/components/LoadCompletedButton.vue
  src/components/SortorderDropdown.vue
  src/components/TaskBody.vue
  src/components/TaskCreateDialog.vue
  src/components/TaskStatusDisplay.vue
  src/mixins/editableItem.js
  src/views/AppContent/Calendar.vue
  src/views/AppNavigation.vue
  src/views/AppSidebar.vue
  src/views/Dashboard.vue
Labels: dependencies, 3. to review

#2771 fix: correctly align actions in task body
  src/components/TaskBody.vue
Labels: bug, design, regression, 3. to review

#2773 fix(style): adjust layout to new clickable area
  src/App.vue
  src/components/HeaderBar.vue
  src/components/TaskBody.vue
  src/components/TaskCheckbox.vue
  src/views/AppContent/task-list.scss
Labels: design, 2. developing

#2777 fix(style): adjust sidebar header layout
  src/components/AppSidebar/CalendarPickerItem.vue
  src/components/AppSidebar/CalendarPickerOption.vue
  src/components/AppSidebar/CheckboxItem.vue
  src/components/AppSidebar/DateTimePickerItem.vue
Labels: design, 3. to review

#2778 fix(style): adjust sidebar body layout
  src/components/AppSidebar/MultiselectItem.vue
  src/components/AppSidebar/MultiselectOption.vue
  src/components/AppSidebar/SliderItem.vue
  src/components/AppSidebar/TagsItem.vue
  src/components/AppSidebar/TextItem.vue
Labels: design, 3. to review

#2779 fix(style): adjust alarm list
  src/components/AppSidebar/Alarm/AlarmList.vue
Labels: design, 2. developing

#2780 fix(style): remove bold font weight from sidebar
  src/components/AppSidebar/CalendarPickerItem.vue
  src/components/AppSidebar/CalendarPickerOption.vue
  src/components/AppSidebar/CheckboxItem.vue
  src/components/AppSidebar/DateTimePickerItem.vue
  src/components/AppSidebar/MultiselectItem.vue
  src/components/AppSidebar/MultiselectOption.vue
  src/components/AppSidebar/SliderItem.vue
  src/components/AppSidebar/TagsItem.vue
  src/components/AppSidebar/TextItem.vue
Labels: design, 3. to review
